=== chibeepatag/SchedulingWithStax/Schedules/person.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:co="tao"
	targetNamespace="tao" elementFormDefault="qualified">
<!-- This is correct
	<element name="person">
		<complexType>
			<sequence>
				<element name="name">
					<complexType>
						<sequence>
							<element name="firstname" type="string" maxOccurs="1" />
							<element name="lastname" type="string" maxOccurs="1" />
						</sequence>
					</complexType>
				</element>
				<element name="school" type="string" />
				<element name="address">
					<complexType>
						<sequence>
							<element name="street" type="string" maxOccurs="1" />
							<element name="city" type="string" maxOccurs="1" />
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
 -->
	<element name="person">
		<complexType>
			<sequence>
				<element name="name" type="co:name" />
				<element name="school" type="string" />
				<element name="address" type="co:address" />
			</sequence>
		</complexType>
	</element>

	
		<complexType name="name">
			<sequence>
				<element name="firstname" type="string" maxOccurs="1" />
				<element name="lastname" type="string" maxOccurs="1" />
			</sequence>
		</complexType>
	

	
		<complexType name="address">
			<sequence>
				<element name="street" type="string" maxOccurs="1" />
				<element name="city" type="string" maxOccurs="1" />
			</sequence>
		</complexType>
	
</schema>

=== chibeepatag/SchedulingWithStax/Schedules/person.xml
<?xml version="1.0" encoding="UTF-8"?>
<person 
    xmlns="tao" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
    xsi:schemaLocation="tao  person.xsd"
>
     <name>
     	<firstname>Celine</firstname>
     	<lastname>Patag</lastname>
     </name>
     <school>Carnegie Mellon</school>
     <address>
     	<street>11 Samar</street>
     	<city>Quezon City</city>
     </address>     
</person>
